services:
  pihole:
    container_name: pihole
    build:
      context: ./docker/pihole/
      dockerfile: Dockerfile
    environment:
      TZ: ${PIHOLE_TIMEZONE:-Melbourne/Australia}
      WEBPASSWORD: ${PIHOLE_PASSWORD:-password}
    volumes:
      - ./docker/pihole/etc/:/etc/pihole/
      - ./docker/pihole/dnsmasq.d/:/etc/dnsmasq.d/
      - ./docker/pihole/log/:/var/log/pihole/
      - ./docker/pihole/admin/:/var/www/html/admin/
    ports:
      - "${PIHOLE_DNS_PORT:-53}:53/tcp"
      - "${PIHOLE_DNS_PORT:-53}:53/udp"
      - "${PIHOLE_DHCP_PORT:-67}:67/udp"
      - "${PIHOLE_HTTP_PORT:-80}:80/tcp"
    restart: unless-stopped